spring:
  profiles: test

# Current directory is default
qc:
  file-location: api/testfile.json
---
spring:
  profiles: local

# Current directory is default
qc:
  file-location: testfile.json
---
qc:
  update-interval: 5000
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: GET
